const imageBase = 'https://images.unsplash.com'

export const professionalExperience = [
  {
    id: 'student-management-system',
    number: '01',
    company: 'El-Shaddai Baptist Schools',
    role: 'Student Management System Developer',
    category: 'Software Development',
    date: 'October 2025 - Present',
    shortDescription: 'A full-stack system for student records and academic information.',
    fullDescription: 'I designed and developed a full-stack Student Management System for managing student records and academic information. The work brought together responsive interfaces, authentication, a centralized database and backend functionality.',
    responsibilities: ['Designed and developed the system', 'Implemented secure user authentication', 'Built a centralized database', 'Created responsive interfaces', 'Developed backend functionality', 'Improved student data management'],
    technologies: ['Full-stack development', 'Authentication', 'Database design', 'Frontend development', 'Backend development'],
    learnings: ['Building software around real information workflows', 'Connecting frontend experiences to backend systems', 'Thinking carefully about access and data organization'],
    image: `${imageBase}/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A team working together around a laptop',
    highlights: ['Student information systems', 'Responsive interfaces', 'Centralized data'],
  },
  {
    id: 'charismo-homes',
    number: '02',
    company: 'Charismo Homes',
    role: 'Media & Website Manager',
    category: 'Technology, Media & Real Estate',
    date: 'Date to confirm',
    shortDescription: 'Using technology and digital media to support a real estate business.',
    fullDescription: "I work at Charismo Homes, a real estate firm, as the Media and Website Manager. The role sits between technology, media, marketing and real estate, helping the business maintain its digital presence and present its properties and services online.",
    responsibilities: ['Managing and maintaining the company website', 'Managing digital content and online presence', "Creating and supporting content for the company's social media platforms", "Managing the company's TikTok presence", 'Supporting brand visibility and digital marketing', 'Working with ERP and software systems', 'Helping present properties and services digitally', 'Using technology and digital platforms to support the business'],
    technologies: ['Website management', 'Digital media', 'Content', 'Social media', 'Brand visibility', 'Business technology'],
    learnings: ['How technology connects with business and marketing', 'Communicating through customer-facing digital experiences', 'Supporting a real business through digital platforms'],
    image: `${imageBase}/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A modern home exterior in warm light',
    highlights: ['Technology x Media x Marketing x Real Estate', 'Website and online presence', 'Digital property presentation'],
  },
  {
    id: 'lasaco-assurance',
    number: '03',
    company: 'Lasaco Assurance PLC',
    role: 'ICT Support Intern',
    category: 'ICT & Software Support',
    date: 'January 2025 - June 2025',
    shortDescription: 'Practical support across IT infrastructure, applications and digital records.',
    fullDescription: 'I provided technical support while gaining early professional experience across ICT support and software/web development. The role included helping staff, maintaining systems and supporting the smooth operation of the department’s IT infrastructure.',
    responsibilities: ['Assisted staff with computer setup', 'Installed software', 'Troubleshot hardware and software problems', 'Assisted with internal applications and websites', 'Supported development, testing and maintenance', 'Managed digital records', 'Assisted with network and system maintenance', 'Updated software'],
    technologies: ['Computer setup', 'Software installation', 'Troubleshooting', 'Internal applications', 'Websites', 'IT infrastructure'],
    learnings: ['Industry-standard development practices', 'Supporting people as well as systems', 'How dependable IT operations are maintained'],
    image: `${imageBase}/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A laptop and notebook in a focused work environment',
    highlights: ['ICT support', 'Software and web maintenance', 'Network and system support'],
  },
  {
    id: 'uwaci',
    number: '04',
    company: 'UWACI',
    role: 'Backend Engineering',
    category: 'Backend Engineering',
    date: 'Current professional experience',
    shortDescription: 'Hands-on growth inside a real backend engineering environment.',
    fullDescription: 'At UWACI, I am gaining hands-on experience working inside an existing backend codebase. The work connects Python, APIs, data, testing and integration hardening while I continue growing into backend engineering.',
    responsibilities: ['Developing with Python and FastAPI', 'Working with PostgreSQL, SQLAlchemy and Pydantic', 'Working with async programming and APIs', 'Writing and using automated tests', 'Working inside an existing backend codebase', 'Contributing to traffic module testing and integration hardening'],
    technologies: ['Python', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'Pydantic', 'Async programming', 'Automated testing'],
    learnings: ['How backend systems fit together behind an interface', 'Working carefully within an existing codebase', 'Growing through real engineering tasks and tests'],
    image: `${imageBase}/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Server racks in a technical environment',
    highlights: ['API development', 'Backend codebase experience', 'Traffic module testing'],
  },
  {
    id: 'project-lead',
    number: '05',
    company: 'Academic Projects',
    role: 'Project Lead',
    category: 'Project Leadership',
    date: '2022 - 2026',
    shortDescription: 'Leading software projects from planning through presentation.',
    fullDescription: 'I led multiple software development projects, coordinating people and progress while collaborating with team members to solve technical challenges and present project outcomes.',
    responsibilities: ['Planned projects', 'Coordinated execution', 'Delegated responsibilities', 'Coordinated team members', 'Monitored project progress', 'Presented project outcomes', 'Collaborated on technical challenges'],
    technologies: ['Project planning', 'Team coordination', 'Delegation', 'Technical collaboration'],
    learnings: ['Project ownership', 'Leading collaboratively', 'Communicating technical work clearly'],
    image: `${imageBase}/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1600&q=85`,
    alt: 'People collaborating around a table',
    highlights: ['Planning', 'Coordination', 'Project presentation'],
  },
  {
    id: 'coding-instructor',
    number: '06',
    company: 'Volunteer',
    role: 'Coding Instructor',
    category: 'Community & Education',
    date: '2024',
    shortDescription: 'Teaching coding fundamentals through practical, interactive lessons.',
    fullDescription: 'I taught coding fundamentals to primary school students through interactive and practical lessons. The experience focused on making programming approachable, encouraging problem-solving and fostering interest in technology.',
    responsibilities: ['Developed learning materials', 'Guided students through programming exercises', 'Encouraged problem-solving', 'Helped foster interest in technology'],
    technologies: ['Coding fundamentals', 'Teaching', 'Learning materials', 'Communication'],
    learnings: ['Explaining technical ideas clearly', 'Adapting lessons to learners', 'Making space for questions and curiosity'],
    image: `${imageBase}/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A classroom with learning materials',
    highlights: ['Interactive lessons', 'Primary school students', 'Technology education'],
  },
]

export const leadershipExperience = [
  {
    id: 'grace-chapel-president',
    number: '07',
    company: 'Babcock University',
    role: 'Grace Chapel Graduating Class President',
    category: 'Leadership',
    date: '2025/2026',
    shortDescription: 'Leading the planning and execution of Grace Chapel Graduating Class Week.',
    fullDescription: 'I led and coordinated the planning and execution of Grace Chapel Graduating Class Week, working with an executive team, church leaders, guest speakers, sponsors and external partners.',
    responsibilities: ['Led an executive team', 'Managed event logistics from conception to completion', 'Secured and managed sponsorships exceeding ₦2 million', 'Engaged sponsors', 'Prepared sponsorship proposals and reports', 'Maintained accountability for funds received', 'Organized leadership meetings and panel sessions', 'Coordinated fundraising', 'Managed stakeholder communication', 'Collaborated with church leaders, guest speakers and external partners'],
    technologies: ['Leadership', 'Event logistics', 'Sponsorship', 'Stakeholder communication', 'Fundraising'],
    learnings: ['Leading people toward a shared outcome', 'Managing responsibility and accountability', 'Communicating across different stakeholders'],
    image: `${imageBase}/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A group of people gathered together',
    highlights: ['Executive team leadership', 'Sponsorship management', 'Graduating Class Week'],
  },
]
