const imageBase = 'https://images.unsplash.com'

export const professionalExperience = [
  {
    id: 'student-management-system',
    number: '01',
    company: 'El-Shaddai Baptist Schools',
    role: 'Student Management System Developer',
    category: 'Software Development',
    date: 'October 2025 - Present',
    shortDescription: 'A full-stack system for student records and academic information.',
    fullDescription: 'I designed and developed a full-stack Student Management System for managing student records and academic information. The work brought together responsive interfaces, authentication, a centralized database and backend functionality.',
    responsibilities: ['Designed and developed the system', 'Implemented secure user authentication', 'Built a centralized database', 'Created responsive interfaces', 'Developed backend functionality', 'Improved student data management'],
    technologies: ['Full-stack development', 'Authentication', 'Database design', 'Frontend development', 'Backend development'],
    learnings: ['Building software around real information workflows', 'Connecting frontend experiences to backend systems', 'Thinking carefully about access and data organization'],
    image: `${imageBase}/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A team working together around a laptop',
    highlights: ['Student information systems', 'Responsive interfaces', 'Centralized data'],
  },
  {
    id: 'charismo-homes',
    number: '02',
    company: 'Charismo Homes',
    role: 'Media & Website Manager',
    category: 'Technology, Media & Real Estate',
    date: 'Date to confirm',
    shortDescription: 'Using technology and digital media to support a real estate business.',
    fullDescription: "I work at Charismo Homes, a real estate firm, as the Media and Website Manager. The role sits between technology, media, marketing and real estate, helping the business maintain its digital presence and present its properties and services online.",
    responsibilities: ['Managing and maintaining the company website', 'Managing digital content and online presence', "Creating and supporting content for the company's social media platforms", "Managing the company's TikTok presence", 'Supporting brand visibility and digital marketing', 'Working with ERP and software systems', 'Helping present properties and services digitally', 'Using technology and digital platforms to support the business'],
    technologies: ['Website management', 'Digital media', 'Content', 'Social media', 'Brand visibility', 'Business technology'],
    learnings: ['How technology connects with business and marketing', 'Communicating through customer-facing digital experiences', 'Supporting a real business through digital platforms'],
    image: `${imageBase}/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A modern home exterior in warm light',
    highlights: ['Technology x Media x Marketing x Real Estate', 'Website and online presence', 'Digital property presentation'],
  },
  {
    id: 'lasaco-assurance',
    number: '03',
    company: 'Lasaco Assurance PLC',
    role: 'ICT Support Intern',
    category: 'ICT & Software Support',
    date: 'January 2025 - June 2025',
    shortDescription: 'Practical support across IT infrastructure, applications and digital records.',
    fullDescription: 'I provided technical support while gaining early professional experience across ICT support and software/web development. The role included helping staff, maintaining systems and supporting the smooth operation of the department’s IT infrastructure.',
    responsibilities: ['Assisted staff with computer setup', 'Installed software', 'Troubleshot hardware and software problems', 'Assisted with internal applications and websites', 'Supported development, testing and maintenance', 'Managed digital records', 'Assisted with network and system maintenance', 'Updated software'],
    technologies: ['Computer setup', 'Software installation', 'Troubleshooting', 'Internal applications', 'Websites', 'IT infrastructure'],
    learnings: ['Industry-standard development practices', 'Supporting people as well as systems', 'How dependable IT operations are maintained'],
    image: `${imageBase}/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A laptop and notebook in a focused work environment',
    highlights: ['ICT support', 'Software and web maintenance', 'Network and system support'],
  },
  {
    id: 'uwaci',
    number: '04',
    company: 'UWACI',
    role: 'Backend Engineering',
    category: 'Backend Engineering',
    date: 'Current professional experience',
    shortDescription: 'Hands-on growth inside a real backend engineering environment.',
    fullDescription: 'At UWACI, I am gaining hands-on experience working inside an existing backend codebase. The work connects Python, APIs, data, testing and integration hardening while I continue growing into backend engineering.',
    responsibilities: ['Developing with Python and FastAPI', 'Working with PostgreSQL, SQLAlchemy and Pydantic', 'Working with async programming and APIs', 'Writing and using automated tests', 'Working inside an existing backend codebase', 'Contributing to traffic module testing and integration hardening'],
    technologies: ['Python', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'Pydantic', 'Async programming', 'Automated testing'],
    learnings: ['How backend systems fit together behind an interface', 'Working carefully within an existing codebase', 'Growing through real engineering tasks and tests'],
    image: `${imageBase}/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Server racks in a technical environment',
    highlights: ['API development', 'Backend codebase experience', 'Traffic module testing'],
  },
]
