const imageBase = 'https://images.unsplash.com'

export const journeyData = [
  {
    id: 'computer-science',
    number: '01',
    title: 'Computer Science Student',
    shortDescription: 'The foundation.',
    subtitle: 'The foundation beneath everything else.',
    image: `${imageBase}/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Books and a notebook on a study desk',
    story: 'Computer Science is the starting point: a space to understand how ideas become systems, and how patient learning creates room for better questions.',
    learnings: ['Computer science foundations', 'Structured problem solving', 'Learning through practice'],
    highlights: ['Studying Computer Science', 'Building a foundation for software and AI'],
    technologies: ['Programming', 'Algorithms', 'Computer systems'],
    reflection: 'Every later chapter still carries something I learned here.',
    quote: 'Start with the foundations. Let curiosity do the rest.',
  },
  {
    id: 'learning-to-code',
    number: '02',
    title: 'Learning to Code',
    shortDescription: 'Where curiosity became a skill.',
    subtitle: 'Where curiosity became a skill.',
    image: `${imageBase}/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Laptop showing code on a desk',
    story: 'Learning to code turned abstract curiosity into something I could practise. Each small program, broken layout and stubborn bug made the distance between an idea and a working thing feel a little shorter.',
    learnings: ['JavaScript', 'React', 'Python', 'Problem solving', 'Consistency'],
    highlights: ['Built my first website', 'Started building personal projects', 'Solved difficult bugs', 'Discovered an interest in backend development'],
    technologies: ['JavaScript', 'React', 'Python'],
    reflection: 'Still learning. Still building. Still excited.',
    quote: 'A little progress is still a working program.',
  },
  {
    id: 'personal-projects',
    number: '03',
    title: 'Building Personal Projects',
    shortDescription: 'Turning ideas into things I could actually make.',
    subtitle: 'Turning ideas into things I could actually make.',
    image: `${imageBase}/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Creative sketches and a laptop',
    story: 'Personal projects became a way to follow questions all the way to an outcome. They gave me space to combine code, design and experimentation without needing every answer before starting.',
    learnings: ['Turning ideas into prototypes', 'Designing around a user', 'Learning by making'],
    highlights: ['FeedSmart', 'EduManage', 'Ayo Game'],
    technologies: ['Python', 'React', 'Product thinking'],
    reflection: 'The unfinished ideas are often the ones that teach me the most.',
    quote: 'Make the thing. Then listen to what it teaches you.',
  },
  {
    id: 'internships',
    number: '04',
    title: 'Internships',
    shortDescription: 'Taking what I learned into real-world environments.',
    subtitle: 'Taking what I learned into real-world environments.',
    image: `${imageBase}/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A bright professional workspace',
    story: 'Internships and work environments brought a different kind of learning: seeing how people, processes and technical decisions meet outside a classroom or personal project.',
    learnings: ['Working in real environments', 'Technical support and problem solving', 'Learning from existing systems'],
    highlights: ['Charismo Homes', 'Lasaco Assurance', 'SIWES / Technical Support'],
    technologies: ['Technical support', 'Digital tools', 'Communication'],
    reflection: 'Real work makes the details matter in a different way.',
    quote: 'Experience is another kind of classroom.',
  },
  {
    id: 'creative-work',
    number: '05',
    title: 'Creative Work',
    shortDescription: 'The part of me that exists beyond code.',
    subtitle: 'The part of me that exists beyond code.',
    image: `${imageBase}/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Design materials and a creative workspace',
    story: 'Creative work is where visual thinking, storytelling and making things by hand stay close. Graphic design, branding, content creation, craft and crochet all remind me that building is not limited to a screen.',
    learnings: ['Graphic design', 'Branding', 'Visual storytelling', 'Craft and crochet'],
    highlights: ['Church and event design', 'Content creation', 'Exploring visual identity'],
    technologies: ['Design tools', 'Visual composition', 'Storytelling'],
    reflection: 'Creativity is not a side road. It changes how I see the main one.',
    quote: 'Good ideas need both structure and feeling.',
  },
  {
    id: 'ai-experimentation',
    number: '06',
    title: 'AI Experimentation',
    shortDescription: 'Exploring what technology can make possible.',
    subtitle: 'Exploring what technology can make possible.',
    image: `${imageBase}/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Abstract artificial intelligence visualization',
    story: 'AI became a place to experiment with possibility: forecasting, intelligent systems and the questions that appear when technology starts helping us make decisions.',
    learnings: ['AI experimentation', 'Forecasting', 'Thinking about useful intelligent systems'],
    highlights: ['FeedSmart food management system', 'Exploring demand forecasting', 'Multilingual AI ideas'],
    technologies: ['Python', 'Forecasting', 'Machine learning'],
    reflection: 'The interesting part is not only what AI can do, but what it should help us do.',
    quote: 'Possibility is more useful when it has a purpose.',
  },
  {
    id: 'backend-engineering',
    number: '07',
    title: 'Backend Engineering',
    shortDescription: 'Going deeper into how things work behind the scenes.',
    subtitle: 'Going deeper into how things work behind the scenes.',
    image: `${imageBase}/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1600&q=85`,
    alt: 'Server racks glowing in a dark technical environment',
    story: 'Backend engineering is a growing direction for me: learning how APIs, databases and server-side systems fit together, and how good architecture makes a product more dependable. I am still exploring this work, one system and test at a time.',
    learnings: ['APIs and server-side development', 'Databases and data modelling', 'Testing and backend architecture', 'Async programming'],
    highlights: ['Working with Python and FastAPI', 'Exploring PostgreSQL and SQLAlchemy', 'Learning how systems fit behind an interface'],
    technologies: ['Python', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'Async APIs'],
    reflection: 'The deeper I look, the more interesting the invisible parts become.',
    quote: 'Build the part people do not see so the part they do can feel simple.',
  },
  {
    id: 'uwaci',
    number: '08',
    title: 'UWACI',
    shortDescription: 'My current chapter in professional backend engineering.',
    subtitle: 'A specific professional chapter in the story.',
    image: `${imageBase}/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=85`,
    alt: 'People collaborating around a table with laptops',
    story: 'UWACI is a professional chapter where backend engineering became connected to a real codebase and real engineering tasks. The work has included a privacy-first multilingual AI platform, APIs, backend infrastructure and learning through implementation.',
    learnings: ['Working within an existing engineering codebase', 'API development with FastAPI', 'Automated testing and integration hardening', 'Learning through real engineering tasks'],
    highlights: ['Python and FastAPI', 'PostgreSQL, SQLAlchemy and Pydantic', 'Async APIs', 'Traffic module testing and integration hardening'],
    technologies: ['Python', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'Pydantic', 'Automated testing'],
    reflection: 'Professional work makes growth feel tangible: every task leaves a clearer next question.',
    quote: 'A real codebase teaches you to be curious and careful at the same time.',
  },
  {
    id: 'whats-next',
    number: '09',
    title: "What's Next?",
    shortDescription: 'Still being written.',
    subtitle: 'An open chapter, still being written.',
    image: `${imageBase}/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=85`,
    alt: 'A quiet road leading toward a bright horizon',
    open: true,
    story: "There are still technologies I want to learn, things I want to build, places I want to go, and ideas I have not figured out yet. This chapter is still being written.",
    learnings: ['Keep asking better questions', 'Make room for the unexpected', 'Stay open to the next useful challenge'],
    highlights: ['Future projects', 'New technologies', 'Ideas still taking shape'],
    technologies: ['Curiosity', 'Courage', 'Attention'],
    reflection: 'Maybe the next chapter includes you.',
    quote: 'The story is not finished yet.',
  },
]
