export const featuredProjects = [
  {
    id: 'feedsmart',
    number: '01',
    title: 'FeedSmart',
    category: 'AI / Food systems',
    year: 'Exploration',
    shortDescription: 'An AI-based food management system focused on reducing food waste through demand forecasting and meal planning.',
    longDescription: 'FeedSmart explores a practical question: when attendance changes, how can food preparation become a little less guesswork?',
    role: 'AI / product exploration',
    technologies: ['Python', 'Demand forecasting', 'Data modelling'],
    problem: 'Preparing meals for a changing student population is difficult when the expected number of people is not known in advance. Too much creates waste; too little creates a different problem.',
    approach: 'The system explores historical meal information, meal type and attendance patterns to estimate expected demand and support better preparation decisions.',
    features: ['Historical meal data', 'Attendance patterns', 'Demand estimation', 'Suggested preparation quantities'],
    challenges: 'The interesting part is translating messy, human attendance patterns into information a planning decision can actually use.',
    outcome: 'A working exploration of how forecasting can support food planning. Exact model performance remains a TODO until the project data and evaluation are finalised.',
    reflection: 'I like this project because the technology points back to something very human: making enough for people, without making more than we need.',
    visual: 'feedsmart',
    status: 'Exploration',
    links: [],
    featured: true,
  },
  {
    id: 'edumanage',
    number: '02',
    title: 'EduManage',
    category: 'Student management system',
    year: '2025 - present',
    shortDescription: 'A full-stack student management platform for El-Shaddai Baptist Schools.',
    longDescription: 'EduManage brings student records and academic information into a more central, structured workflow.',
    role: 'Full-stack developer',
    technologies: ['Authentication', 'Database design', 'Frontend development', 'Backend functionality'],
    problem: 'Schools work with large amounts of student and academic information. When that information is scattered, everyday administration becomes slower and harder to keep consistent.',
    approach: 'I designed and developed a full-stack system with secure authentication, centralised database storage, responsive interfaces and backend functionality.',
    features: ['Student records', 'Attendance', 'Academic information', 'Payments', 'Scheduling', 'Authentication', 'Database management'],
    challenges: 'The work is less about making a flashy dashboard and more about making many connected information flows feel understandable and dependable.',
    outcome: 'A working school information platform designed around the needs of El-Shaddai Baptist Schools.',
    reflection: 'This was a useful reminder that good software often looks simple on the surface because someone has taken care of the complexity underneath.',
    visual: 'edumanage',
    status: 'Active project',
    links: [{ label: 'Visit live site', href: 'https://elshaddaibaptistschools.com/' }],
    featured: true,
  },
  {
    id: 'ayo-game',
    number: '03',
    title: 'Ayo Game',
    category: 'Python game',
    year: 'Academic project',
    shortDescription: 'A digital implementation of the traditional Ayo board game using object-oriented programming.',
    longDescription: 'Ayo Game translates a traditional game of pits, stones and decisions into a playable digital system.',
    role: 'Game logic developer',
    technologies: ['Python', 'Object-oriented programming', 'Game algorithms'],
    problem: 'A board game is a collection of rules that have to remain true no matter how a player interacts with it. The challenge is making those rules feel natural in software.',
    approach: 'I modelled the board, validated moves, distributed stones, tracked scores and evaluated win conditions. A decision-making algorithm provides an AI opponent for single-player play.',
    features: ['Move validation', 'Stone distribution', 'Board state management', 'Score tracking', 'Win-condition evaluation', 'AI opponent'],
    challenges: 'The board can change after every move, so each step has to update the state correctly before the next decision is allowed.',
    outcome: 'A playable Python implementation that uses object-oriented programming to represent the game and its rules.',
    reflection: 'Ayo made algorithms feel less abstract. The rules were already there; my job was to teach a computer how to respect them.',
    visual: 'ayo',
    status: 'Completed project',
    links: [],
    featured: true,
  },
  {
    id: 'uwaci',
    number: '04',
    title: 'UWACI',
    category: 'Backend engineering',
    year: 'Current experience',
    shortDescription: 'A privacy-first multilingual platform supporting voice-first and text-capable AI experiences.',
    longDescription: 'UWACI is the larger platform. My contribution has been within the backend engineering team, particularly around the Traffic module and its testing and integration hardening.',
    role: 'Backend engineering contributor',
    technologies: ['Python', 'FastAPI', 'Pydantic', 'SQLAlchemy', 'asyncpg', 'PostgreSQL / Supabase', 'Alembic', 'Testing'],
    problem: 'Real backend systems have to remain dependable as modules, APIs and integrations interact. Small contract or validation gaps can become much bigger problems at the edges.',
    approach: 'I worked inside an existing backend codebase, strengthening the Traffic module through unit tests, service tests, API contract tests, validation tests, error handling and regression coverage.',
    features: ['Multilingual AI platform context', 'Voice and text-capable experiences', 'Traffic module testing', 'API and integration hardening'],
    challenges: 'The work required understanding an existing system carefully before changing it, then making the tests say something useful about its real behaviour.',
    outcome: 'Hands-on experience contributing to backend infrastructure and improving confidence around an existing module. I did not design the entire UWACI platform or Traffic architecture.',
    reflection: 'This is the kind of work that makes engineering feel real: reading closely, finding the edges and helping a system hold together.',
    visual: 'uwaci',
    status: 'Professional experience',
    links: [],
    featured: true,
  },
  {
    id: 'resq',
    number: '05',
    title: 'ResQ',
    category: 'AI / Emergency response',
    year: 'March 2026',
    shortDescription: 'A digital platform designed to streamline emergency response and incident reporting.',
    longDescription: 'ResQ focuses on making emergency reporting and request management clearer for people who need help and the responders handling those requests.',
    role: 'Product and software contributor',
    technologies: ['Responsive interface', 'Backend services', 'Request management', 'Communication flows'],
    problem: 'Emergency situations require fast, clear communication. Friction in reporting or managing a request can make an already difficult situation harder.',
    approach: 'The platform brings emergency reporting, request management and communication between users and responders into one responsive experience.',
    features: ['Emergency reporting', 'Request management', 'User / responder communication', 'Responsive interface', 'Backend services'],
    challenges: 'The experience needs to feel direct and understandable without inventing complexity that is not supported by the project.',
    outcome: 'A documented digital platform concept for streamlining incident reporting and response coordination.',
    reflection: 'ResQ is a reminder that product decisions matter most when someone is already under pressure.',
    visual: 'resq',
    status: 'Project',
    links: [],
    featured: true,
  },
  {
    id: 'verified',
    number: '06',
    title: 'Verified',
    category: 'Insurance / AI prototype',
    year: 'Squad Hackathon 3.0',
    shortDescription: 'Proof of Life: an AI-powered fraud-detection prototype for insurance claims.',
    longDescription: 'Verified was designed as a hackathon prototype to help insurers assess claims using several signals before payment.',
    role: 'ML / AI engineer',
    technologies: ['Python', 'FastAPI', 'XGBoost', 'EfficientNet', 'Isolation Forest', 'SHAP'],
    problem: 'Insurance claims can contain different kinds of evidence: behaviour, documents, images, prices, policy information and identity. Reviewing those signals together is difficult.',
    approach: 'I worked on the Python FastAPI ML service. The wider prototype combined five analysis modules into a trust score, claim tier and recommended action.',
    features: ['Behavioural anomaly analysis', 'Photo forensics', 'Document intelligence', 'Price intelligence', 'Policy and identity checks'],
    challenges: 'The interesting technical problem was not one magic model. It was combining different kinds of signals while keeping the result explainable enough to inspect.',
    outcome: 'A hackathon prototype concept with a scoring flow from five modules to a 0-100 trust score and VERIFIED / REVIEW / FLAGGED tiers. It is presented as a prototype, not a proven production system.',
    reflection: 'Verified let me work on the part of AI I enjoy most: turning several imperfect clues into a system people can question and understand.',
    visual: 'verified',
    status: 'Hackathon prototype',
    links: [],
    featured: true,
  },
]
