export const whatIDoAreas = [
  {
    id: 'software',
    number: '01',
    title: 'Software',
    shortDescription: 'Web applications, frontend development, backend systems and APIs.',
    intro: 'Where ideas become things that actually run.',
    fullDescription: 'I like software because it gives an idea somewhere to live. I move between interfaces, data, APIs and the small decisions that make a product feel clear and useful.',
    colour: 'software',
    visual: 'browser',
    skills: ['React', 'JavaScript', 'HTML / CSS', 'Python', 'FastAPI', 'REST APIs', 'PostgreSQL', 'SQL', 'Git / GitHub'],
    projects: [
      { title: 'EduManage', type: 'Student management system', detail: 'Records, attendance, academics, payments and scheduling brought into one workflow.' },
      { title: 'Ayo Game', type: 'Python game', detail: 'A strategic traditional game rebuilt as an interactive software experience.' },
      { title: 'UWACI', type: 'Backend engineering', detail: 'Python, FastAPI, PostgreSQL, async APIs and automated testing inside a real codebase.' },
    ],
  },
  {
    id: 'ai',
    number: '02',
    title: 'AI',
    shortDescription: 'Machine learning, AI experimentation, forecasting and intelligent systems.',
    intro: 'Where curiosity meets data.',
    fullDescription: 'I am exploring AI by building with it: asking useful questions of data, testing what a model can tell us and staying honest about what the system still cannot know.',
    colour: 'ai',
    visual: 'network',
    skills: ['Python', 'Demand forecasting', 'Predictive systems', 'Data exploration', 'Machine learning', 'TensorFlow', 'PyTorch', 'Scikit-learn'],
    projects: [
      { title: 'FeedSmart', type: 'Smart food management', detail: 'Demand forecasting to estimate meal demand and help determine appropriate preparation quantities.' },
    ],
  },
  {
    id: 'creative',
    number: '03',
    title: 'Creative',
    shortDescription: 'UI design, branding, visual content, websites and digital experiences.',
    intro: 'Where the other side of my brain gets involved.',
    fullDescription: 'Design is how I make the technical work feel human. I am interested in visual systems, storytelling, texture and the little details that make someone want to stay.',
    colour: 'creative',
    visual: 'collage',
    skills: ['UI design', 'Website design', 'Branding', 'Graphic design', 'Social content', 'Event design', 'Visual storytelling', 'Crochet + crafting'],
    projects: [
      { title: 'Digital experiences', type: 'Design practice', detail: 'Interfaces, websites and visual systems shaped around clarity, feeling and personality.' },
      { title: 'Creative direction', type: 'Visual storytelling', detail: 'Bringing colour, type, composition and content together for a distinct point of view.' },
    ],
  },
  {
    id: 'building',
    number: '04',
    title: 'Building',
    shortDescription: 'Turning ideas into real products, experiments and projects.',
    intro: 'I have an idea. Naturally, I want to make it.',
    fullDescription: 'Building is the part where curiosity gets practical. I like taking a half-formed thought through experiments, broken versions, fixes and the satisfying moment when it becomes real.',
    colour: 'building',
    visual: 'stack',
    skills: ['Ideas', 'Experiments', 'Product thinking', 'Prototyping', 'Problem solving', 'Project leadership', 'Learning in public'],
    projects: [
      { title: 'FeedSmart', type: 'AI food systems', detail: 'A project shaped from a real problem: reducing food waste through better demand estimation.' },
      { title: 'EduManage', type: 'Product building', detail: 'A full workflow for managing student information, built around how people actually work.' },
      { title: 'Ayo Game', type: 'Playful experiment', detail: 'A chance to explore logic, interaction and the joy of making a system playable.' },
    ],
  },
]
